script: bundle exec rake test

before_install: sudo rake ci:dependencies

bundler_args: --without tools

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode

matrix:
  include:
    - rvm: 2.0.0
      env: ENABLE_SLOW_TESTS=true

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head